[package]
name = "healthpi-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.79"
healthpi-model = { path = "../healthpi-model", features = ["serde"] }

itertools = "0.12.1"
mockall = "0.12.1"
reqwest = { version = "0.12.3", features = ["json"] }
thiserror = "1.0.58"
