name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_URL: sqlite:${{ github.workspace }}/healthpi.db
  RUSTFLAGS: "-Dwarnings"
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install libdbus-1-dev pkg-config && cargo install migrant --features sqlite
    - name: Run migration
      working-directory: healthpi-db
      run: migrant setup && migrant apply
    - name: Run format check
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test
